Fix info Settings.java
Elytrium/VelocityTools pull request #38
Opened 2024-01-26 13:19 UTC by MishaNeYT

1.20 is 1.20/1.20.1

https://github.com/PaperMC/Velocity/blob/dev/3.0.0/api/src/main/java/com/velocitypowered/api/network/ProtocolVersion.java

![image](https://github.com/Elytrium/VelocityTools/assets/68995871/bfc090e9-0341-4693-99ad-1bb4b39495d8)

2024-01-26 13:39 UTC, MishaNeYT commented
Так же ошибка возникает, я с версии 1.20.1, но плагин блокирует join/ping, хотя стоит 1.20 (1.20.1 не существует)

2024-01-26 14:06 UTC, UserNugget requested changes
Спасибо за PR, но судя по всему 1.20.4 также надо убрать [по той же причине](https://github.com/PaperMC/Velocity/blob/b9b11665b9a3926bdbf45986e6e0f736ca0d01cd/api/src/main/java/com/velocitypowered/api/network/ProtocolVersion.java#L68)

2024-01-26 14:08 UTC, MishaNeYT commented
Верно!

2024-01-27 09:32 UTC, UserNugget approved these changes

2024-02-27 22:02 UTC, mdxd44 commented
supercedused by eb161f3

2024-02-27 22:02 UTC, closed without merging